export const STUDENT_LOGIN_REQUEST = "STUDENT_LOGIN_REQUEST";
export const STUDENT_LOGIN_SUCCESS = "STUDENT_LOGIN_SUCCESS";
export const STUDENT_LOGIN_FAIL = "STUDENT_LOGIN_FAIL";

export const STUDENT_LOGOUT_REQUEST = "STUDENT_LOGOUT_REQUEST";
export const STUDENT_LOGOUT_SUCCESS = "STUDENT_LOGOUT_SUCCESS";
export const STUDENT_LOGOUT_FAIL = "STUDENT_LOGOUT_FAIL";

export const STUDENT_PROFILE_REQUEST = "STUDENT_PROFILE_REQUEST"
export const STUDENT_PROFILE_SUCCESS = "STUDENT_PROFILE_SUCCESS";
export const STUDENT_PROFILE_FAIL = "STUDENT_PROFILE_FAIL";
