//--------------------------CREATE COURSE CATEGORY ----------------//
export const CREATE_COURSE_CATEGORY_REQUEST = "CREATE_COURSE_CATEGORY_REQUEST";
export const CREATE_COURSE_CATEGORY_SUCCSESS =
  "CREATE_COURSE_CATEGORY_SUCCSESS";
export const CREATE_COURSE_CATEGORY_FAIL = "CREATE_COURSE_CATEGORY_FAIL";

//--------------------------ALL COURSE CATEGORY ----------------//

export const ALL_COURSE_CATEGORY_REQUEST = "ALL_COURSE_CATEGORY_REQUEST";
export const ALL_COURSE_CATEGORY_SUCCSESS = "ALL_COURSE_CATEGORY_SUCCSESS";
export const ALL_COURSE_CATEGORY_FAIL = "ALL_COURSE_CATEGORY_FAIL";

//--------------------------DELETE COURSE CATEGORY ----------------//

export const DELETE_COURSE_CATEGORY_REQUEST = "DELETE_COURSE_CATEGORY_REQUEST";
export const DELETE_COURSE_CATEGORY_SUCCSESS =
  "DELETE_COURSE_CATEGORY_SUCCSESS";
export const DELETE_COURSE_CATEGORY_FAIL = "DELETE_COURSE_CATEGORY_FAIL";

//--------------------------SINGLE VIEW COURSE CATEGORY ----------------//
 export const SINGLE_COURSE_CATEGORY_REQUEST ="SINGLE_COURSE_CATEGORY_REQUEST"
 export const SINGLE_COURSE_CATEGORY_SUCCESS ="SINGLE_COURSE_CATEGORY_SUCCESS"
 export const SINGLE_COURSE_CATEGORY_FAIL ="SINGLE_COURSE_CATEGORY_FAIL"

//--------------------------UPDATE COURSE CATEGORY ----------------//
 export const UPDATE_COURSE_CATEGORY_REQUEST ="UPDATE_COURSE_CATEGORY_REQUEST"
 export const UPDATE_COURSE_CATEGORY_SUCCESS ="UPDATE_COURSE_CATEGORY_SUCCESS"
 export const UPDATE_COURSE_CATEGORY_FAIL ="UPDATE_COURSE_CATEGORY_FAIL"